### ISSUE TITLE
What are the downsides/risks in comparison to traditional SSR?

### ISSUE THREAD

**Issue by robhrt7** [alt-j/fast-react-render#13]
Hi,

First of all, I'm very impressed with the results we got during the tests of the library. You did really a great job here!

But as we all know, such huge performance gains usually come at a cost, so I wonder, which kind of risks and limitations this SSR solution implies comparing to `ReactDOMServer.renderToStaticMarkup`?

I've also noticed in some of the issues, that you mentioned you're using it in production at Yandex, is it still the case?

Cheers

**Comment by alt-j** [comment]
The biggest trouble you can encounter using our rendering instead of native is the re-rendering that occurs when the application is initialized on the client. Details [here](https://github.com/alt-j/fast-react-render/issues/7).
